Question 11:

The goal is a single function that can be called repeatedly to produce all the featuremaps we need, regardless of the layers

function can take in featuremaps and filter matricies as arguments --> produces a featuremap

In [ ]:
#Libraries

import numpy as np

In [ ]:
# Question 11 (a)

# 20x20 2 dimensional array I which is the image -- all ones
# 10x10 2 dimensional array F which is the convultional filter -- all ones

I = np.ones((20,20))
F = np.ones((10,10))


print(I)
print('********************************************************************************************************')
print(F)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.

In [ ]:
# Question 11 (b) ----- working

import numpy as np

I = np.ones((20,20))
F = 0.01*np.ones((10,10))
s=1

#print(I)
#print('********************************************************************************************************')
#print(F)

# X and W is two arrays, ie so one is the image and the other is the convultional filter
# s is the stride

# outputs a 2d array Y, which is the result of convolution of X by filter W with stride s

def conOne(I,F,s):
  # must get the dimensions of the input. arrays and then configure the loop accordingly

  # get dimensions of the inputs
  img_dimension= I.shape
  filter_dimension = F.shape

  # Calculate the Featuremap Dimensions, we dont have have padding in this case
  Featuremap_indexs =[]
  Featuremap_indexs.append(int(((img_dimension[0]-filter_dimension[0])/s)+1))
  Featuremap_indexs.append(int(((img_dimension[1]-filter_dimension[1])/s)+1))


  # Define the featuremap and initialize to random values
  featuremap=np.ones((Featuremap_indexs[0],Featuremap_indexs[1]))

  #Define a submatrix of x -- which is the same length as filter
  submatrix=np.ones((filter_dimension[0],filter_dimension[1]))

  #initiliaze positions


  count_down=Featuremap_indexs[0]
  count_right=Featuremap_indexs[1]

  print(count_down)
  print(count_right)

  i=0
  j=0

  for a in range(0,count_down):
    for b in range(0,count_right):
      for k in range(filter_dimension[0]):
        for l in range(filter_dimension[1]):
          submatrix[k][l]=I[i+k][j+l]
      print(submatrix)
      print('******')
      featuremap[a][b]=np.sum(np.multiply(F,submatrix))
      j=j+s
      if b==(count_right-1):
        i=i+s
        j=0
  print(featuremap)







In [ ]:
#Tester Cell ------------ working

import numpy as np

I=np.array([[1,2,3,4,5],[1,1,1,1,1],[1,2,3,4,5],[1,1,1,1,1],[-1,-1,-1,-1,-1]])
F=np.array([[1,1],[-1,-1]])

s=2

# must get the dimensions of the input. arrays and then configure the loop accordingly

# get dimensions of the inputs
img_dimension= I.shape
filter_dimension = F.shape

# Calculate the Featuremap Dimensions, we dont have have padding in this case
Featuremap_indexs =[]
Featuremap_indexs.append(int(((img_dimension[0]-filter_dimension[0])/s)+1))
Featuremap_indexs.append(int(((img_dimension[1]-filter_dimension[1])/s)+1))


# Define the featuremap and initialize to random values
featuremap=np.ones((Featuremap_indexs[0],Featuremap_indexs[1]))

#Define a submatrix of x -- which is the same length as filter
submatrix=np.ones((filter_dimension[0],filter_dimension[1]))

#initiliaze positions


count_down=Featuremap_indexs[0]
count_right=Featuremap_indexs[1]

print(count_down)
print(count_right)

i=0
j=0

for a in range(0,count_down):
  for b in range(0,count_right):
    for k in range(filter_dimension[0]):
      for l in range(filter_dimension[1]):
        submatrix[k][l]=I[i+k][j+l]
    print(submatrix)
    print('******')
    featuremap[a][b]=np.sum(np.multiply(F,submatrix))
    j=j+s
    if b==(count_right-1):
      i=i+s
      j=0
print(featuremap)


2
2
[[1. 2.]
 [1. 1.]]
******
[[3. 4.]
 [1. 1.]]
******
[[1. 2.]
 [1. 1.]]
******
[[3. 4.]
 [1. 1.]]
******
[[1. 5.]
 [1. 5.]]


In [ ]:
import numpy as np
# the first number tells you the amount of matricies, the last two are the dimensions of each matrix
x=np.ones((4,2,2))
x[1]=-1*x[1]

x[2][0][0]=0
x[2][1][1]=0

x[3][0][0]=-1
x[3][1][1]=-1

print(x)

[[[ 1.  1.]
  [ 1.  1.]]

 [[-1. -1.]
  [-1. -1.]]

 [[ 0.  1.]
  [ 1.  0.]]

 [[-1.  1.]
  [ 1. -1.]]]


In [ ]:
# Question 11D ------- tester cell


import numpy as np

I=np.ones(4,10,10)
I[]
F=np.ones((4,2,2))
F[1]=-1*F[1]

F[2][0][0]=0
F[2][1][1]=0

F[3][0][0]=-1
F[3][1][1]=-1

s=1

# the filter in the below is a 3d one
def conOne(I,F,s):
  # must get the dimensions of the input. arrays and then configure the loop accordingly

  # get dimensions of the inputs
  img_dimension= I.shape
  filter_dimension = F.shape

  # Calculate the Featuremap Dimensions, we dont have have padding in this case
  Featuremap_indexs =[]
  Featuremap_indexs.append(int(((img_dimension[0]-filter_dimension[1])/s)+1))
  Featuremap_indexs.append(int(((img_dimension[1]-filter_dimension[2])/s)+1))


  # Define the featuremap and initialize to random values
  featuremap=np.ones((filter_dimension[0],Featuremap_indexs[0],Featuremap_indexs[1]))


  #Define a submatrix of x -- which is the same length as filter
  submatrix=np.ones((filter_dimension[1],filter_dimension[2]))

  #initiliaze positions


  count_down=Featuremap_indexs[0]
  count_right=Featuremap_indexs[1]

  #print(count_down)
  #print(count_right)

  i=0
  j=0

  for z in range(filter_dimension[0]):
    i=0
    j=0
    for a in range(0,count_down):
      for b in range(0,count_right):
        for k in range(filter_dimension[1]):
          for l in range(filter_dimension[2]):
            submatrix[k][l]=I[i+k][j+l]
        #print(submatrix)
        #print('******')
        featuremap[z][a][b]=np.sum(np.multiply(F[z],submatrix))
        j=j+s
        if b==(count_right-1):
          i=i+s
          j=0

  print(featuremap)



TypeError: ignored

In [ ]:
I = np.ones((20,20))

F=np.ones((4,10,10))
F[0]=0.01*F[0]
F[1]=0.01*F[1]
F[2]=0.02*F[2]
F[3]=0.02*F[3]

conOne(I,F,2)


[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[2. 2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2. 2.]]

 [[2. 2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2. 2.]]]


In [ ]:
# conThree testcell -- working on example below

#image

I = np.ones((2,5,5))

I[0][0][0:5]=0.25
I[0][2][0:5]=0.5
I[0][3][0:5]=-1
I[0][4][0:5]=-4

I[1][0][0:5]=4
I[1][2][0:5]=3
print(I)

F=np.ones((4,2,2))
F[1]=-1*F[1]

F[2][0][0]=0
F[2][1][1]=0

F[3][0][0]=-1
F[3][1][1]=-1

print(F)
s=2
# must get the dimensions of the input. arrays and then configure the loop accordingly

# get dimensions of the inputs
img_dimension= I.shape
filter_dimension = F.shape

# Calculate the Featuremap Dimensions, we dont have have padding in this case
Featuremap_indexs =[]
Featuremap_indexs.append(int(((img_dimension[1]-filter_dimension[1])/s)+1))
Featuremap_indexs.append(int(((img_dimension[2]-filter_dimension[2])/s)+1))


# Define the featuremap and initialize to random values
featuremap=np.ones((filter_dimension[0],Featuremap_indexs[0],Featuremap_indexs[1]))


#Define a submatrix of x -- which is the same length as filter
submatrix=np.ones((filter_dimension[1],filter_dimension[2]))

#initiliaze positions


count_down=Featuremap_indexs[0]
count_right=Featuremap_indexs[1]

#print(count_down)
#print(count_right)

i=0
j=0

for t in range(img_dimension[0]):
  for z in range(filter_dimension[0]):
    i=0
    j=0
    for a in range(0,count_down):
      for b in range(0,count_right):
        for k in range(filter_dimension[1]):
          for l in range(filter_dimension[2]):
            submatrix[k][l]=I[t][i+k][j+l]
        #print(submatrix)
        #print('******')
        featuremap[z][a][b]=np.sum(np.multiply(F[z],submatrix))
        j=j+s
        if b==(count_right-1):
          i=i+s
          j=0

  print(featuremap)

[[[ 0.25  0.25  0.25  0.25  0.25]
  [ 1.    1.    1.    1.    1.  ]
  [ 0.5   0.5   0.5   0.5   0.5 ]
  [-1.   -1.   -1.   -1.   -1.  ]
  [-4.   -4.   -4.   -4.   -4.  ]]

 [[ 4.    4.    4.    4.    4.  ]
  [ 1.    1.    1.    1.    1.  ]
  [ 3.    3.    3.    3.    3.  ]
  [ 1.    1.    1.    1.    1.  ]
  [ 1.    1.    1.    1.    1.  ]]]
[[[ 1.  1.]
  [ 1.  1.]]

 [[-1. -1.]
  [-1. -1.]]

 [[ 0.  1.]
  [ 1.  0.]]

 [[-1.  1.]
  [ 1. -1.]]]
[[[ 2.5   2.5 ]
  [-1.   -1.  ]]

 [[-2.5  -2.5 ]
  [ 1.    1.  ]]

 [[ 1.25  1.25]
  [-0.5  -0.5 ]]

 [[ 0.    0.  ]
  [ 0.    0.  ]]]
[[[ 10.  10.]
  [  8.   8.]]

 [[-10. -10.]
  [ -8.  -8.]]

 [[  5.   5.]
  [  4.   4.]]

 [[  0.   0.]
  [  0.   0.]]]


In [ ]:
# Question 11E

#change F to python list that has two 3d arrays

#one of them has 4 matricies that are 10x10 -- 0.01 and 0.02
#other one has three new 4x4 with equal entries: 1/36,1/18,1/9

I = np.ones((20,20))

a=np.ones((4,10,10))
a[0]=0.01*a[0]
a[1]=0.01*a[1]
a[2]=0.02*a[2]
a[3]=0.02*a[3]

b=np.ones((3,4,4))
b[0]=(1/36)*b[0]
b[1]=(1/18)*b[1]
b[2]=(1/9)*b[2]

F=[]
F.append(a)
F.append(b)


#modify function to take a 3d input image, and call it con three

def conThree(I,F,s):
  # get dimensions of the inputs
  img_dimension= I.shape
  filter_dimension = F.shape
  print(img_dimension)
  # Calculate the Featuremap Dimensions, we dont have have padding in this case
  Featuremap_indexs =[]
  Featuremap_indexs.append(int(((img_dimension[1]-filter_dimension[1])/s)+1))
  Featuremap_indexs.append(int(((img_dimension[2]-filter_dimension[2])/s)+1))


  # Define the featuremap and initialize to random values
  featuremap=np.ones((filter_dimension[0]*img_dimension[0],Featuremap_indexs[0],Featuremap_indexs[1]))
  print(featuremap.shape)
  #featuremap=[]

  #Define a submatrix of x -- which is the same length as filter
  submatrix=np.ones((filter_dimension[1],filter_dimension[2]))

  #initiliaze positions


  count_down=Featuremap_indexs[0]
  count_right=Featuremap_indexs[1]

  #print(count_down)
  #print(count_right)

  i=0
  j=0
  counter=0
  for t in range(img_dimension[0]):
    for z in range(filter_dimension[0]):
      i=0
      j=0
      for a in range(0,count_down):
        for b in range(0,count_right):
          for k in range(filter_dimension[1]):
            for l in range(filter_dimension[2]):
              submatrix[k][l]=I[t][i+k][j+l]
          #print(submatrix)
          #print('******')
          #print(counter)
          featuremap[counter][a][b]=np.sum(np.multiply(F[z],submatrix))
          #featuremap=np.sum(np.multiply(F[z],submatrix))
          j=j+s
          if b==(count_right-1):
            i=i+s
            j=0
      counter=counter+1
  #print(featuremap)
  return featuremap


In [ ]:
#Question 11E Continued

I = np.ones((1,20,20))

a=np.ones((4,10,10))
a[0]=0.01*a[0]
a[1]=0.01*a[1]
a[2]=0.02*a[2]
a[3]=0.02*a[3]

b=np.ones((3,4,4))
b[0]=(1/36)*b[0]
b[1]=(1/18)*b[1]
b[2]=(1/9)*b[2]

F=[]
F.append(a)
F.append(b)

Y=conThree(I,F[0],2) #gives a resulting featuremap
#print(Y)
result=conThree(Y,F[1],1)
print(result)

(1, 20, 20)
(4, 6, 6)
(4, 6, 6)
(12, 3, 3)
[[[0.44444444 0.44444444 0.44444444]
  [0.44444444 0.44444444 0.44444444]
  [0.44444444 0.44444444 0.44444444]]

 [[0.88888889 0.88888889 0.88888889]
  [0.88888889 0.88888889 0.88888889]
  [0.88888889 0.88888889 0.88888889]]

 [[1.77777778 1.77777778 1.77777778]
  [1.77777778 1.77777778 1.77777778]
  [1.77777778 1.77777778 1.77777778]]

 [[0.44444444 0.44444444 0.44444444]
  [0.44444444 0.44444444 0.44444444]
  [0.44444444 0.44444444 0.44444444]]

 [[0.88888889 0.88888889 0.88888889]
  [0.88888889 0.88888889 0.88888889]
  [0.88888889 0.88888889 0.88888889]]

 [[1.77777778 1.77777778 1.77777778]
  [1.77777778 1.77777778 1.77777778]
  [1.77777778 1.77777778 1.77777778]]

 [[0.88888889 0.88888889 0.88888889]
  [0.88888889 0.88888889 0.88888889]
  [0.88888889 0.88888889 0.88888889]]

 [[1.77777778 1.77777778 1.77777778]
  [1.77777778 1.77777778 1.77777778]
  [1.77777778 1.77777778 1.77777778]]

 [[3.55555556 3.55555556 3.55555556]
  [3.55555556 3.

In [ ]:
conThree(Y,F[1],1)

(4, 6, 6)
(12, 3, 3)


array([[[0.44444444, 0.44444444, 0.44444444],
        [0.44444444, 0.44444444, 0.44444444],
        [0.44444444, 0.44444444, 0.44444444]],

       [[0.88888889, 0.88888889, 0.88888889],
        [0.88888889, 0.88888889, 0.88888889],
        [0.88888889, 0.88888889, 0.88888889]],

       [[1.77777778, 1.77777778, 1.77777778],
        [1.77777778, 1.77777778, 1.77777778],
        [1.77777778, 1.77777778, 1.77777778]],

       [[0.44444444, 0.44444444, 0.44444444],
        [0.44444444, 0.44444444, 0.44444444],
        [0.44444444, 0.44444444, 0.44444444]],

       [[0.88888889, 0.88888889, 0.88888889],
        [0.88888889, 0.88888889, 0.88888889],
        [0.88888889, 0.88888889, 0.88888889]],

       [[1.77777778, 1.77777778, 1.77777778],
        [1.77777778, 1.77777778, 1.77777778],
        [1.77777778, 1.77777778, 1.77777778]],

       [[0.88888889, 0.88888889, 0.88888889],
        [0.88888889, 0.88888889, 0.88888889],
        [0.88888889, 0.88888889, 0.88888889]],

       [[1.77777778,